DROP TABLE if exists USER_CONFIG;
DROP TABLE if exists USER_BALANCE;
DROP TABLE if exists SIX_NUMBER_ORDER;
DROP TABLE if exists SIX_NUMBER_ORDER_DETAIL;

CREATE TABLE USER_CONFIG
(
    UID  VARCHAR(250) NOT NULL PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    PASS VARCHAR(250) NOT NULL,
    ROLE VARCHAR(250) NOT NULL
);
CREATE TABLE USER_BALANCE
(
    "UID"   VARCHAR2(250) NOT NULL,
    VERSION LONG          NOT NULL default 0,
    MONEY   DOUBLE PRECISION
);

CREATE TABLE SIX_NUMBER_ORDER
(
    "UID"       VARCHAR2(250) NOT NULL,
    MONEY       DOUBLE PRECISION,
    CREATE_TIME timestamp     not null,
    ORDER_ID    VARCHAR2(50)  NOT NULL PRIMARY KEY,
);

CREATE TABLE SIX_NUMBER_ORDER_DETAIL
(
    ID       VARCHAR2(50) NOT NULL PRIMARY KEY,
    NUMBER   INT          NOT NULL,
    ORDER_ID VARCHAR2(50)
);

create INDEX IDX_LO001 on SIX_NUMBER_ORDER (UID, ORDER_ID);
create INDEX IDX_LO002 on SIX_NUMBER_ORDER (UID);
create INDEX IDX_LO003 on SIX_NUMBER_ORDER_DETAIL (ORDER_ID);

INSERT INTO USER_CONFIG (UID, NAME, PASS, ROLE)
VALUES ('fenrir', 'fenrir', 'fenrir', 'USER');

INSERT INTO USER_CONFIG (UID, NAME, PASS, ROLE)
VALUES ('ADMIN', 'fenrir_ADMIN', 'PASSWORD', 'ADMIN');

INSERT INTO USER_BALANCE (UID, MONEY)
VALUES ('fenrir', 10000);

INSERT INTO USER_BALANCE (UID, MONEY)
VALUES ('ADMIN', 15000);